version: '2'
services:
  sonoshttpapi:
    image: Keesromkes/rpi-docker-node-sonos-http-api
    restart: always
    network_mode: host
    volumes:
      - ./settings:/app/settings
      - ./clips:/app/clips
      - ./cache:/app/cache
      - ./presets:/app/presets
